#!/usr/bin/env bash
# Install Nginx with the following configurations:
#+    Listen on port 80.
#+    Return a page containing "Hello World!" when queried
#+     at the root with a curl GET request.
#+    Configure /redirect_me as a "301 Moved Permanently".
#+    Include a custom 404 page containing "Ceci n'est pas une page".
#+    Contain a custom HTTP header named X-Served-By.
#+    The value of the HTTP header is the hostname of the running server.

apt-get install -y nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https//YouTube.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
